services:
    app:
        build: .
        container_name: springboot-app
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://98.84.118.128:3306/:3306/properties?createDatabaseIfNotExist=true
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=my-secret-pw
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        restart: on-failure
